/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Panel: typeof import('primevue/panel')['default']
    RecordingList: typeof import('./../components/RecordingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleBuilder: typeof import('./../components/RuleBuilder.vue')['default']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
